apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-huggingface-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gin-huggingface
  template:
    metadata:
      labels:
        app: gin-huggingface
    spec:
      containers:
      - name: gin-huggingface
        image: hecha/gin-huggingface:latest
        ports:
        - containerPort: 8080
        env:
        - name: HUGGING_FACE_API_KEY
          value: "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"
        - name: PORT
          value: "8080"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"